name: Generate Data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v2

      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: danteryder
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Use Node.js 20 for GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: runner.os == 'Linux'
